#!/bin/bash

# This restarts the local PostgreSQL server and launches the command-line app
# in Python

if ! pg_isready > /dev/null
then sudo service postgresql restart
fi

cd ~/projects/random-act

source venv/bin/activate

python app/loop.py